### ISSUE TITLE
Unable to download AppleIncRootCertificate.cer

### ISSUE THREAD

**Issue by curioustushar** [stendahls/cert-downloader#1]
```AppleIncRootCertificate.cer``` is now forced to redirect to HTTPS with 301.

So we are unable to download certificates an empty file is generated and we get the following error.

![image](https://user-images.githubusercontent.com/12570521/104298066-92169a00-54e9-11eb-95b2-c7f3893c2695.png)

**Comment by kokarn** [comment]
Thanks to your PR this is now available on 2.0.0 on NPM.
